---
apiVersion: v1
type: Opaque
metadata:
  name: cart-redis-pass
  annotations:
    kots.io/exclude: '{{repl (ConfigOptionEquals "generate-passwords" "1") }}'
data:
  password: '{{repl ConfigOption "cart-password" | Base64Encode }}'
---
apiVersion: v1
type: Opaque
metadata:
  name: cart-redis-pass
  annotations:
    kots.io/exclude: '{{repl (ConfigOptionEquals "generate-passwords" "0") }}'
data:
  password: '{{repl RandomString 35 | Base64Encode }}'
