---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: catalog-mongo-pass
  annotations:
    kots.io/exclude: '{{repl (ConfigOptionEquals "generate-passwords" "1") }}'
data:
  password: '{{repl ConfigOption "catalog-password"}}'  
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: catalog-mongo-pass
  annotations:
    kots.io/exclude: '{{repl (ConfigOptionEquals "generate-passwords" "0") }}'
data:
  password: '{{repl RandomString 35 | Base64Encode }}'
