---
apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: acme-fitness
spec:
  groups:
  - name: acme-fitness
    title: Services
    description: Configures the high-level parameters for the services
    items:
    - name: domain
      title: Domain
      help_text: "The base domain for exposed ACME fitness services"
      type: text
      required: true
      default: "acme-fitness.local"
  - name: tls
    title: TLS
    description: Configures TLS for the exposed services
    - name: tls-issuer-type
      title: Issuer Type
      help_text: "Type of certificate issuer to use on to issue certificates"
      type: select_one
        items:
        - name: issuer
          title: Issuer
        - name: cluster-issuer
          title: Cluster Issuer
    - name: tls-issuer-name
      title: Issuer Name
      help_text: "Which issuer/cluster issuer should to use to generate certificates"
      type: text
      required: true
  - name: passwords
    title: Passwords
    description: "Passwords for ACME fitness data stores"
    - name: generate-passwords
      title: Generate Passwords?
      type: bool
      default: "1"
    - name: cart-password
      title: Cart Datastore Passowrd
      when: '{{repl (ConfigOptionEquals "generate_passwords" "0")}}'
      type: text
      required: '{{repl (ConfigOptionEquals "generate_passwords" "0")}}'
    - name: catalog-password
      title: Catalog Database Passowrd
      when: '{{repl (ConfigOptionEquals "generate_passwords" "0")}}'
      type: text
      required: '{{repl (ConfigOptionEquals "generate_passwords" "0")}}'
    - name: order-password
      title: Order Database Passowrd
      when: '{{repl (ConfigOptionEquals "generate_passwords" "0")}}'
      type: text
      required: '{{repl (ConfigOptionEquals "generate_passwords" "0")}}'
    - name: user-cache-password
      title: User Cache Passowrd
      when: '{{repl (ConfigOptionEquals "generate_passwords" "0")}}'
      type: text
      required: '{{repl (ConfigOptionEquals "generate_passwords" "0")}}'
    - name: user-db-password
      title: User Database Passowrd
      when: '{{repl (ConfigOptionEquals "generate_passwords" "0")}}'
      type: text
      required: '{{repl (ConfigOptionEquals "generate_passwords" "0")}}'
