---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: acme-fitness
spec:
  title: Acme Fitness
  icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAAAzCAYAAAAQPQPAAAAEGWlDQ1BrQ0dDb2xvclNwYWNlR2VuZXJpY1JHQgAAOI2NVV1oHFUUPrtzZyMkzlNsNIV0qD8NJQ2TVjShtLp/3d02bpZJNtoi6GT27s6Yyc44M7v9oU9FUHwx6psUxL+3gCAo9Q/bPrQvlQol2tQgKD60+INQ6Ium65k7M5lpurHeZe58853vnnvuuWfvBei5qliWkRQBFpquLRcy4nOHj4g9K5CEh6AXBqFXUR0rXalMAjZPC3e1W99Dwntf2dXd/p+tt0YdFSBxH2Kz5qgLiI8B8KdVy3YBevqRHz/qWh72Yui3MUDEL3q44WPXw3M+fo1pZuQs4tOIBVVTaoiXEI/MxfhGDPsxsNZfoE1q66ro5aJim3XdoLFw72H+n23BaIXzbcOnz5mfPoTvYVz7KzUl5+FRxEuqkp9G/Ajia219thzg25abkRE/BpDc3pqvphHvRFys2weqvp+krbWKIX7nhDbzLOItiM8358pTwdirqpPFnMF2xLc1WvLyOwTAibpbmvHHcvttU57y5+XqNZrLe3lE/Pq8eUj2fXKfOe3pfOjzhJYtB/yll5SDFcSDiH+hRkH25+L+sdxKEAMZahrlSX8ukqMOWy/jXW2m6M9LDBc31B9LFuv6gVKg/0Szi3KAr1kGq1GMjU/aLbnq6/lRxc4XfJ98hTargX++DbMJBSiYMIe9Ck1YAxFkKEAG3xbYaKmDDgYyFK0UGYpfoWYXG+fAPPI6tJnNwb7ClP7IyF+D+bjOtCpkhz6CFrIa/I6sFtNl8auFXGMTP34sNwI/JhkgEtmDz14ySfaRcTIBInmKPE32kxyyE2Tv+thKbEVePDfW/byMM1Kmm0XdObS7oGD/MypMXFPXrCwOtoYjyyn7BV29/MZfsVzpLDdRtuIZnbpXzvlf+ev8MvYr/Gqk4H/kV/G3csdazLuyTMPsbFhzd1UabQbjFvDRmcWJxR3zcfHkVw9GfpbJmeev9F08WW8uDkaslwX6avlWGU6NRKz0g/SHtCy9J30o/ca9zX3Kfc19zn3BXQKRO8ud477hLnAfc1/G9mrzGlrfexZ5GLdn6ZZrrEohI2wVHhZywjbhUWEy8icMCGNCUdiBlq3r+xafL549HQ5jH+an+1y+LlYBifuxAvRN/lVVVOlwlCkdVm9NOL5BE4wkQ2SMlDZU97hX86EilU/lUmkQUztTE6mx1EEPh7OmdqBtAvv8HdWpbrJS6tJj3n0CWdM6busNzRV3S9KTYhqvNiqWmuroiKgYhshMjmhTh9ptWhsF7970j/SbMrsPE1suR5z7DMC+P/Hs+y7ijrQAlhyAgccjbhjPygfeBTjzhNqy28EdkUh8C+DU9+z2v/oyeH791OncxHOs5y2AtTc7nb/f73TWPkD/qwBnjX8BoJ98VQNcC+8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAFZaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJYTVAgQ29yZSA1LjQuMCI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PSIiCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIj4KICAgICAgICAgPHRpZmY6T3JpZW50YXRpb24+MTwvdGlmZjpPcmllbnRhdGlvbj4KICAgICAgPC9yZGY6RGVzY3JpcHRpb24+CiAgIDwvcmRmOlJERj4KPC94OnhtcG1ldGE+CkzCJ1kAACDDSURBVHgB7V0HeFVVtl4hvQcICTWEEDpKEURwRIp0LKMIOo4FdSyI4+iAdeZZRt5TFNGnjqLo54iKgigWmlTLgHRRSuiKlBBaIL2Q+/5/3bNuzr1JMCJ+bz6T9X337LP73muvvdreJwkSEQ9+tVANDAQFBYnH45HYevUl5+gRvxrR8QmSdzwbaUH41aLUDzmniNQ5RV6NyCJRGZCwEpIbSXS9RA2j4uI0S8s4xBefmKTE13PYZfLc0tXyxCdLJe2szkp8sXXroXwt8Rk+qxsSYzX2V6dOHU9c/URPfHKjSnEAovSlR8fG6nub9u09Uzfv9cw47vHMyvV4Jn3xjaYHR0Z5QiMiPSBYX52ajNvqzL3GckBytYSkZIkCtztx5LAcP3hAzhs8XO791/syefkmeeDtjyStbXvldvGJDXQzR8YlaDhozDip26SJFGTnSF52njTr2ElG3H2/nCzIl2hwTYrpWqgeBkKqV+y3VQpcT8rKyiQ766BOrP9V10q/P4yW5l17SHhMlJwsLZOUju0ltePZ8tTIIbJja4bUbZAseXl5Wr5ph05SWioSHBICYiuTIGzj9G7naV5wSKgXWRTttYToxcUpnjWOAEkgJ0tLpH7dBOl15bXSe+Q10rRjFwkOD5OSwiIpzPUSWVF+mdRLTZVbX5om4/t1F9AbON5RiY4Ikxjoeh4QsBdgmOA1PqmhRktJmbVQbQzUOBEMfU+Rc+7wy+Xa/54sKef0kJMgpqK8fCk7eRJGbB2pExqm3K3gRJ606NpNxr32ruQcOigxILKQwmIJIvGV2y7aXhDr1sLPxkCNI0CKXsIhiN8CiNSSggKH8IIkLDJKwsLDpTTnuISACIMgqgvzCqT7pVfK1ff+XXKzMuU46p7IPqZ52hDsN4rgY4ezNBoCsVwL1cdAjSPAk8VFip0DG9ZIIfx2dULCJDwqSsJBeAd3ZMj85yfKI73ayHcL50pEdKScBGfjb8gd4+SCSy7XulnbNktIsCC91Ot0AU3vXLtS8yjeFWr1Py8efuJJQVKjTDZyuODIaNXnXliVIcmt28ju1Stl/ZwPZPqzE/3QNWnpGknpco7kH8+RiJhYOfLDThnTNV1ap6bIfXNXSGyTxhKMLbxn3Xq5+8KuIuSgILySosJaS9gPk1VHKiVAuijoSqA4adCggQQHB6sFeOwYRI+TF9ikpcfExAh/rGNw/Phxyc3NFbM+w8LCpH5iIhavDqzJUsnMzLSikpycLKGhoWqlHjlyRIqKinz14uDiiI2N9VqXtDIBHCfbLSwslMOHD1c6vqA6weUiExZDVFy85B47Kjc98oQcg1j94J/PaluRCXUlMiJC6kCmHj6wT9p2PEvGz5wvUYnJUgwXS1RcrGR8uUz+fnFfOf/SETLy7gckPy9Xpt53p+zc+K3QEZ2Ddmvh52GgUqdpSGhohXQQQIU0dOVzvNavX+60Zbr7Fx0To/GIiAi/dJaB+NO0qKioCnmRkZGaBsKrkOdun+9VjS8M7YLoPJGxcZ4o/CIwlrjEBr726jZq4kls0kzzrM2klFTNv/jmOzzvHir1vLUv3zNtX55n5jGPZ+yzU3x1rXxMQl0nrdYJbTipTlipxgxCkPz8fGnUqJGMGz9eEuvXl0WLFsu0aW9K3bp1hZzQDeRCID4hx6oLzjZ2zB2S0qyp6k7khO++954sXrRIEpFHLtWmbVu5Y8wY5ZQHs7Lkgfvvl+joaOWyjz76qDRPSZEccMyXX54imzZtVC586NAhufzyy2XYsGFSUlKinI5joB8uPDxCNm7cKJMmTZL4+HjJyclRDsr8kIhIKcZcihlxQSHaNzgGbmcQgzPdEnDTAvwIHftcpNyT1EUuXwRXze9GXScZny+SRR/OlAYpqeCmRySXhkkV0kEbqn1UioEKBEgkGgF2795d7rn7bq2YBNFIAiShHD9xwms5Ok0aYQ0ZOlRem/oaCNfrE7Met2RsVQKkCCUBNmvWTMbeead6Mkjor746VXbt3KHFb7vtNklKStL3efMXKAEmJCQICfD8310gN954ozXrF369cqUSIMdO4imG6I5vkCTHD2XJbc9NlbMu7A+LNleCXKqBab+U5rSOKZpXznhT3njsISmCaB5xzwPSFWe+RQWFSlzETRkMj2DgoOcfb1YCLEU/BSB4+mWqOgExwuTYuIENWJ553DAngFNTUUz1YdxUDJahKsMNTaMoNjZO4qASWBts08qyLf4IVIe4KZlHxlEAq59xruPBgwe1LZaj2pMIdasOxsOyBPZP57tb9bK5cB6QTjp+4o7rSsbgBnoRSBuhUOXYFtUprqO1wbIVCNAmwcyU5s19E0ys7/WfcQLh0OGocxFssHx/4oknKhCfu4yVLS09KXlw+MbERKue2anT2UqAPXv1UjcI6+Ri4qVYbIK5ToodC1YTAx7ljuFyF52dSjRMS5e0TqmSD6YHdbAC0JEcGiGye+VG+WTSPzS/bacuMvTWu4BUjAEFiEwdP/RDjr9pmw7SsGEj6K8HBOJXOWCFhp0E1jMOzw1XGVC3JZGRELiQBw4cqFCMRJeTc0L1YIb8VQUkPBIqdW/+DEyCkZgJJAwSfHFxsRzYv9+K+YVkHO4NQruAhBQoCUNBFyVoh8D3WIzhECScG5hG6WZE6EeAvkTHl9UqvZXWZefG1ShmOTkCEWvc76qrr5azzzpLJz3trbdk544dAn1PO1q58mstb0RLjhMM85HEzF2UApFLSEtLk+ioaCnETglxcypWAJSVeXfmkqVLZf68ecpNuFh0oezYuVPLcBFLnNMIWqOEbatXUH6qIUFC8gPudhIX2pk14SE5kuetc93/PCex4PoFOXnOkZu3b0xauT9vyqR16SaZ8z6RYBDNqcAWsGfPnjJ69Gg1vIg7/miQffrpp/Lxxx/71JhmwMdf7rpLYmJBRCB2EsiCBZ/JrFnvg+gbqtE2bNhwueSSi5VYmU+gQcf25s6dK7Nnz9a0/v0vkquvvkq5zyuvviobvvlGRowYIf369ZMJEybIvn37lPhatmwpd/3lL8pcjJMRr8s+/1zexnpSCmVnZ+sYSXx9+/eXoUOGKJFxU73w4otgIjt1zenYJyEePXpUbr7lVtBFRzXutm3fLk9NnAgOHAduXr55iFn9gQA1hIjUEIjxgPg8y1es8GCHeNq2a6fpGIwHO8ev7MSnngI+PZ5P58zRdGvTwkgYAiBWzevTt58HxOjJ2LpV60x+9llNf/SxxzzYtZ7tO3aivxLPRQMHajqQo+HjEyZo+edfeFHj1raF2BgV0ml8WP5PhdG4FcMyo//xtOd9GBvT9uZ53tpf4Pd752CxxqcjHHbTGC2fkNzwlH2AaDT/5ptv1vEHPiZPnqz5Ns/u3c8NLOJ5aYrX8OnYsaOWfdLBd4WCSHj++ed94xk3/l5fkdvH3KHp/4t8QudOnXzlLrigt+LeV9h5mTnzfS3TtGlTDzifvo+5Y6wHTMKvaO8+fTQvBsYiVCh9f2/GDL8yXG/it0mTJhqS3vw4IDIVTORRVyOr3g7K7XneeZLeMl0ytmxRPQQta1lyTQLdJ4QVy8FtAG3atFGRwnxzw8REl3NO6jLUG1qC67VMa6l1yAkpCg5Bb2uZ1sInejVTH96+qEsR2rVrp7vS9Au2x/5sbHVw7pt/4rg0a9dRL5HqUZvWLH+QI3K3nsBtmKwff5DuF/aVPn+8EeMoN3TYK2fLkKchUfXhmgLXS2jSTBsyHGjfTFHUePGjUQdXnBthB6QDuQnHrdwbcQIlgoXLli2TDh06qLTZtWuX4p15diGC3GbTpk0qXtvCqGNbW7A2lE5cLwNyMxt7ampzTS7B3KiPkVMZFJcUa//HMK59e/eqKkDptHHTRi1C7lrkqF3jx49TTrl27VrlzuSAx1GPQBFL9WHElSNl5JVX6jwzMjLAQeNl9Zq1WoZ9G1RKgIUOIpLB7inDbUItQBQEsnxbZAtpBRMKHbFHonP79zTTuzJSBp2KBHjsWLbqA8nJXqODBE8RynQ3IXnrlj9tg1C3CdSVdDzcFFj0OIwp+2CmXHnfI9J14FApyM3BQpUrgSTISDiYv1s8T5687grtYMTDEyUKOh2P6YKDiR6PqhVRcdGyacli2bXq3zL0r39Xaqxr17Sgm7HfIJIo+qbop58xCPoirfRAoLh67lmv79HySDj7HR0sGxZ137595f1ZH8iAi/oLuJ4Wo+61e/duJbIpL78s/BHWf7NBoiIjpEePHhrnA1xGxWtYWKhuahoXaS3SND+oThB0YfhGiScHuAkhpWTKK6/IX++5x5I1pP5KnJ/A2gwaNEhSYRuAu8lVo0b5lWOEOixhyOBBGv4JIvj9mTP0nQ+25WYUfgRIJJK7HIHsjoPMr1evnu6qzZu3aAOmE5rO4WsVL6E8mwLYpCzUxIAHJ8P8XEzoKHRK6jWEJo0bqysnP997I8WIO6C6L1pVH0Qrd70RG42EhKRICceOdtEfkCoSAWZ6HFyNMOiGWyQFV62KsAFZF1qa3noJhZsnJ+uwPHfZRdLjT2MFsgo5wZIOHZCwf/tWDd0P+ByhP5brOe68eOiPhFatWvmMBG48cjHihiGB3FHniONCKS32OeW58ahfp2DDUq8KAe65oQnUo90WKTcROW8e6jRL8XJs72bR4uUPEqOuf7SmUYKRS5NbMaQOSICaoOFn0EkJrVu3VmOETKMUx5C2ZpRmpCMSH+2HEEojcEraEJyTlfMjQDZItsuCPc49V81nKpzQAZklqS1SGfgQpBHngbErOIE7q8K7xzEmyC3JJTt37qJl4jFJsmsTVURIdcA9IZa3ydHtQlg9d7Zk7dktxRAhtrhWhptp4+eLtVwqLpYGg2OU5kH8gkuQitk2yWH+808Jzziy9+9VYyYYRJnUqp08sXgVLrQegUgOUeOEFxq2LP9C3p3wN+H1/ePOJQXtwHnQOiVQnLo5uHF2pxjm4XBPEB/BCJRjokFHa5LAudh8aDCSQCMxDkIdzIMeAnLXhsnejR7YjxZ0HpbHsdFNY2ArYZ6FUmcOJE7SiIGNgxzWrqYdhWpEdchUDCvDOhUIkLuO0BY7gPDjnj2SuX+fiqFmTZtqmiFQI6fxoAgm0MLbC32D7pc27dpLAvxT1Hci4DwmVEV/RkRk53SWc0FocXFR3MRI/Y939+a98ry291OPuCS25S3FsOxkGUR0lKz6aJa899xEqd+0uayYM1tGwXHdML0tHNYF0qJLdyyyt07ZSQ/KgzgcwggFl/o1gWLVCxZ6idSLHyMZ7yb68ccfJT09XYvTjUQ8VQfc+PSW97Zr1QPb8bWKxbN3EhwJsjKoQIAmXpunpmp50+NI6eYgNndKZQ1WK83BDQe/CzoNETl40EAVOTt37JSz4Rf0QjkS3fE8h7NR6XYDdZgCcG+lIkw6HC4d6mLdh14qSc3TpBSKNvUyZW1a0YuiDOh1329YJ8GGMeSRE4RhI+zL2CwTrx+hpeuok0BkM05BmsEA4qVVnrIYlJWRs8WC0xZoknunWxmGJi6p9xGnWQG+MnfZU70HYkfLBuxauq7Y3/fff6/SLQ0itAR4qArcm5s6J42SUhgyBubns3gcmAa5rnE328HkkDTwCElQsTgsNaACxleBAK1hGgSEPdg5hMMQM1Q+69VPhN52WBVht4NTC1X34Sw0iX3r1m1aq0uXLjrIzVs2S9dzumpaOYK9FWwXDR48GH6xBaoHcZHJkf/r4Yfl31995XdUyJONIuiTA264TboNHQydDBcbbCeiHg6x1d/43sPjlQAP792jt5vZuRkQi177p46lfqMmcmwvcBEWKdPv+7O079VbmnbuJIU58BsSqWgrCCFxHsgVtAHXw5zA27Z5586sipzGVeEXvHIjEc80XjgnGirlFn45hm0Opn9v3Vqu15IoTZzuBiETLrzwQvnXG2/IdmcO5ki3udOSHjhggAwYOFAWfvaZ1rEyGnEejvDwxrg45oSkgkswy4wNUjx3BtIJ4WdAvIRC3/pmwzfKbTp37qy637LPv1CFlX0YQ8LaKvCWCqEVRMlATKx3796KiH5wqlIUE+iIrRagUepGIWFBktTCK5oyVi1XgiUeqH8xrAexS+BCloLA4nBHMAfxZ2++SnZBNw4C16NLhj9c4EAIMYgFJ9j4NcK4M5E7cQy5EkeH3333nSzEGXm0Y0VXe+zWYDVCzkMJEIRDg6I9VB3TsblvDNg3jy9HwbJdgXl9++238hU29NmdOnnnDi7II7wF8+fLDz/8IKNvuEHWrlsnsz/6WNJhiNCIIoEV4NiSwGNUwrQ335TVq1fLpGcmaxm2QcPIcOHHAaNggOQ4Z4gNsaDcqSbmDjhXptq2aStLFi9WP5D2cBoPdVegHk32DevXY2C50unssyULyuxxiEyeHXrBu4TlePK+cTeS83ES/DFuO9Qt9vKgAxLmT31R1i2co6LEJs50liXRZO7y+uG++nCGXDzmHmnRrYcUnMiBCIGV170ni6rriOEJjI/Xrr7fmiH3DuwlvQYMltiUNF0kchES4sHvd7FoheM565uWpFmTraFrsw7BRLNGztCDREYORl2e60k9cPXaNdwNfj3wAyueINETwZ9BPC5nEIgrGqhs458vvSRP4ti1K6QWfzzZ6NunD1xBkcLLJfQJz5zxnswbfQPcMYM13q1bN1jTx+Qfjz3mO83hGGyltRPuAirziTjE5xEbfYCHHQuHRzaEluktNTRdUSOn+TCEH8FfGeAkrC9L9zVLLALM+Plw9kcy6emJ0gJ+LdvNa1YDqQATb3wvhvilHrjus08ZPSVQxB6BcbHqo5lqWAQFQ+wUl0oDcMeGqWmSCaLCN79SCsudd/5wrYsOUVm+cH6l7YbDQDIr3AqUOfOYh2PEzZs3K0fRO4+Ozljs0rWszi8PvbijnpmFzxBS4IpZsw4OYWcs1j7xGB4WLsuXL5cvv/xSXXBUsfZS7QAwn2e/9PdOfPJJWO+ZwjP8/jiS6wNxfAGk0ZdffKFzok5I4FHdQ3/7G6zvZLnppptwJHi1EqBtRG4BPwI0ouoEthsDBK7d4+2cjRFhhJRmKRq6OY0m/JyHs/lM4aW5n9aihc8lYcprYJPWJxdt5cpV+nOXCcV3HG4vO3cYdUDqgiFAbiDStS45KC458GIqbzTPemGSXHj9LZKc1gr+wHx1ZnfvN1A+ef1liMpYySaxoE4+fHx0ScTAdUQXA1027vZogRPRNmbNcxEgjsucClYtCF4BXHz4lYCqFT0OPD2iD9FvXOiTfYeEYkOt+Frux/U4N/AWOQ0Izoe4JxFOe/NfMg2F/nDNNXpWTB2eBMi2yQToBuJ5/4THH9emWqSlSe8Leus7XU926cKPAI3ztG7dSgvSwXkNOqBsb+Sw5caNvbqW6Ypa8DQfJorN0t5XxW2M8ua9lGvedjpyiRASMncdd6nfojsLTmKoDtSHaD0CoqOV27hVa9UR6RdMg0gWEGAIfH9u4DchubASq4LARbZydiWLR2j0LmRmHqxAEFb2l4denNFltWvXbuGFCDqVKU2MAWgfIC5u0FhcgCCQUCkN+aNu6MYrcU4jla6dfBAmoZFzmGBMrAB4pESlirENBs0JEGV0dBQkaLrvogppyI8AbUA88yWch/Pf888/X9/NQcnTEQKtJeoEpwUOtzipbgsoqtOmydZt2+VznH8SLF0jlTxsYcntiCA3ciyvkmp+SVrHnQLk8yIq4fO3X5dzLxuFj9RjpazUg7980FnT86Bo81TEbtlwwU4HTJWg4m6b73Ta+Tl1ePqybfs25VBJULE4BmM47nZOwvdJoJObkol4IrjxyjRzuxjNmHqhhfFgGRKYESjLsY3A83glQF0MFzKb4TYzwT1A66guCLBxk6ayf99elfda0PXwDteVcIpXm9SHH3wg/PEgm2AnJaeo6pdl7fglVhKxefKYLCIafXHOrgGz38at2siW9Wtlx5qvpcvgYXoZtV6TZtKma3fZum41RHJiOQFW0sd/ahJ9jry8wC3TCFKMRpt7fSuM26GHynDLNEu3sNwp7m3J0t0h8R/Ypx8HNC7H28+EOXPm6LEcRR6P5wbAr8Pr+e3atVUCNHbLsvSuBwI75M/aDcy3eAvof/k4f1UrHDsPVX4W2O6yyVZaGY0yn5cPeEZb1TlttnMuPBsXU9vB11cHumMEDJmUdh2UAO0oqtI+fmGibRBrxus0R8w5C6ZTmWVOByKjImXhwkXCiya0cukoDiQGtmuMhiKb1qydBTOd68g6NFCjkE9RbGtrhxO2BlTbSPQMCRw3aSTbuQdo9fw4oFmUjXDTlw0NHz5cK9tj7tx5MmTIYD3wXoxEDsYQol5uK+jk2bUpXjA9lYLN3XgQbh5zfruaqfzVWQMihUovNwLbMCRUWgnziQX3yoETfeDo2+T8K67WE4vKDR50APWAxgm/N4HHuty/eHrrX+mQAhNt8WxxuPia5pwFh4eHQdetjAh/WhUIoxEGoCXbuHETTK/UzfwdaQDjCqoVwe2IJhFRXTDDwX1GPBiWLmGzcypF0UziZXn+7Kz7nHO64TDjMDwdWWphm+qkBMhJ0slMiibwehQLkFsk4h4XLwnwo5+DMOMJzXEiQjDi4zsbJ9iVH+oYgUSpBX7Rw4toWyhuGDfR2S6t0AW5BuYYijkSGrdqK50H9MaZLc8oq6aoYnyApMdrqJsDv6DCT6+1t1wlTxu3hYFFuGEpaRIS6qpezPuAXHTi/rXXXpfJk58RSqcs1yUBtkHOaEQbODz25db36M+l8UZCtJvjbINX6HmMOXLkSDkfZ/Pslzo+r109+sgjggupakXTcJo6dapyNm4QfjfEywgzUY7AOmx77NixcvvttysNkBOmw333EW59EzhP0hfBR4DkJGyQH/7QW02K5v25XJjmdvNh316vL5BHcgQuuHFNXrIkXHLpJfImjIqvVywHsqDsgu2SSM4MMXqJxU5EOBFadOTE1gc3RVULbLplCTgbiY9+Ol67OhWEYGFO4O/CZHxJng9/mOOzO1WdwDzbqFxUgp14WDrT+G4ikYvYB45dAxJi6zatNRrhbCJGrD6tS37P7E6zPPbFdq1PI14SBdfPIAwuLPZL7tUUdwkNOnboqK/MI5AbmmHKOI0PnnIQeK5tc6TDu3379prOB09PHn74EY27b/EoATLVbsG0apWuheyKDdPNamMjhAbOV2ucpJWbPn26PPjgg6pfzJ83VwmCE+TkH3zoIb08aSKZbXCn+ggFk3ADdzQBqq47GW15EXbliCtk+LChikCOjchcsmSJXHrppfoJp+5uWGCBQEZI4Lj1h/HptStvcoUnxxEeFSLbcL2Kjtx6jZvKUVzH+rlArkagL/X111+XVatWadx9lk5c2GbOxCXaZ555xu+bkM+c81Rz8rIB29T0IoTSFwmgCCROrM+1a9bIlClT9BY288nRWI/uH7co3Y8bTy+++KLSgbnYuPb8JoRAnBJotevYQKh56IvfqiyYP08ZAXFkLqal+G6HRMuxHASHfPWVV9VuIHfniYgPsBBKC9C/NHzq6aeBC4/nnXfe0Tjv74Mj6nv/iwZoHj4A0niDBt5vKBo3buxXVwu5HvwuAR16cFlSw16/+53m4kMcjePc2RumpGi44LOFmt+3Xz+Np7dqpeHTkya5WvV/xaJqGZwJe7Db9Z196s+ZYz18gM74dY9P8nyQgzlmFulH59Px4bnfL6vEMx2/GUiftGS1Jxltsh6MEf92rf1qhOAsfnXBSfziNlZc3Kw0nflWh2tm62Zrw3x8/ORXFxvTLw7i8IuzDphERXwFzMfarYBXp5x962NzsHFa3ELr38bO9BAsI0LqEV7/D79Goyf7mw0bNJ27wT7S5vcBPBsuhG5EOHzosBoA3BWk/PHjxmndyy77vdTD399j27wJa7vHjpoKcWC9B2eTpqCaLmLnufvg4lEnZ773WpNdASK3ZR3zQWEiusMoNniti8A2bE6awIczR+8fERdZ+fEsyfpht5wklzS2iGI8D9U4y4M7luWekGVvv6EftfMvn+bxiInlnfbYdHWA4yTXoQQgnsjFqKAzPXCsvFVMo4pXoShBmM+Q5bku7jp8ZxpFH9/Nb8c6jJPDUjpQpaJ+z3WgysI0cibik/gi56XoPNV3wRwDywWOjaoPb2AbsF+OlV8CUlwTSFtMY//MD5yzb1cAQb531POAhfriEKW+d+ZVthvq16vnV4bl7AcdU98xAV8a8wL7DIxbefdYrM3AsDpl+Gc6AuudKh4UG++JMk7icNJTla/NK1/z6uCCWhEXxEeZVFa5U4tA7Xq5k5kOkEPQWcxd49ZfLJ+hfd/BHc9dQyDH4u4x6mc6d4d6yh39iOVsMPQx8UYMdw13j9WjoWS6Ksu7IbAtd57vHbuP3ItOaF6dd6auZ7rHMvfLqAcekwS4oEq50zHGZW++Ils3rIcfMEoKXeP0tVf7ckYw4McRyOnAjn06hrNKvjLkSMaVAvNAKL5y5JBsp6q2mA5C9JV3t2VjcKfxneWtzcAwkEMH1q0qjj9UrmMYeP0tnhlHPfqbXeDxTF6xSdMj8V0xpUZV9WvTfxlufFYwEKlA3YC/qsD0tMry3bLdLLrKyjHNLK3K8qsaA7mh6aqV1TudNLtuPvjWP2vb/DNshXlB8vajD2hzvAlS4L1ddDrN19b5CQyUO4J+ouBvMRt/kk2/GfnjIxOlKY7aimgoxMXIhiULZM18/KkM5POPG1EFqIVfBwMVOOCv081/WKsgKP4ZtsP7fpSGLVpK71HXwiIu1ZOS7MwsmYG/EUMogqOa4ObsmlD7OGMYqHEcULkZDJEwXDAgXH/ff8HB3BDf+haAAMPkq/fflh+3ZSj349/8A/s7Y8iubagiBszwrJjzG06JhS8sBycBvQcNlVunvC1lYRH6Z+H2b9sid/fsIBG4rlUCXZD6pvvPvv2GUfL/NrUaxwGJ6bCoGEX4OcOvkIj6CVJGhzS44hfTXtX0KFzC4O2dWuJTdPzqjxrnYgh1HOz8c2NPLV3j+ajY43n8k6WKh9ikhp7TdelgpWocLs/AnGsm0vgfMom81DbtPM99sd7T5/cjNR7vpJ8BxNYSYzU2ZI3UAdWwgMgN/LcKoTBMSnAh005eQIS18CtjoGYSIJFK6xZEGIUjQfyJFwnGJYCT+ObX0n9lvNc272Dg/wA92M5YK8tm8gAAAABJRU5ErkJggg==
  statusInformers:
    - deployment/cart
    - deployment/cart-redis
    - deployment/catalog
    - deployment/catalog-mongo
    - deployment/frontend
    - deployment/order
    - deployment/order-postgres
    - deployment/payment
    - deployment/pos
    - deployment/users
    - deployment/users-mongo
    - deployment/users-redis
  replicatedRegistryDomain: registry.shortrib.io
    # proxyRegistryDomain: proxy.shortrib.io
  ports:
    - serviceName: frontend
      servicePort: 80
      localPort: 8888
      applicationUrl: "http://frontend"
    - serviceName: pos
      servicePort: 7777
      localPort: 8889
      applicationUrl: "http://pos"
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: acme-fitness
spec:
  descriptor:
    links:
      - description: Open App
        # needs to match applicationUrl in kots-app.yaml
        url: "http://frontend"
---
apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: acme-fitness
spec:
  groups:
    - name: acme-fitness
      title: Services
      description: Configures the high-level parameters for the services
      items:
        - name: domain
          title: Domain
          help_text: "The base domain for exposed ACME fitness services"
          type: text
          required: true
          default: "acme-fitness.local"
    - name: security
      title: Security
      description: Optional security features
      items:
        - name: enable_pod_security
          type: bool
          title: Enable Pod Security
          default: "0"
        - name: pod_security_context
          title: Pod Security Context
          help_text: "Pod security context"
          type: textarea
          when: '{{repl ConfigOptionEquals "enable_pod_security" "1"}}'
    - name: tls
      title: TLS
      description: Configures TLS for the exposed services
      items:
        - name: tls-issuer-type
          title: Issuer Type
          help_text: "Type of certificate issuer to use on to issue certificates"
          type: select_one
          items:
            - name: issuer
              title: Issuer
            - name: cluster-issuer
              title: Cluster Issuer
        - name: tls-issuer-name
          title: Issuer Name
          help_text: "Which issuer/cluster issuer should to use to generate certificates"
          type: text
          required: true
    - name: passwords
      title: Passwords
      description: "Passwords for ACME fitness data stores"
      items:
        - name: generate-passwords
          title: Generate Passwords?
          type: bool
          default: true
        - name: cart-password
          title: Cart Datastore Passowrd
          when: '{{repl (ConfigOptionEquals "generate-passwords" "0")}}'
          type: password
          required: true
        - name: catalog-password
          title: Catalog Database Passowrd
          when: '{{repl (ConfigOptionEquals "generate-passwords" "0")}}'
          type: password
          required: true
        - name: order-password
          title: Order Database Passowrd
          when: '{{repl (ConfigOptionEquals "generate-passwords" "0")}}'
          type: password
          required: true
        - name: user-cache-password
          title: User Cache Passowrd
          when: '{{repl (ConfigOptionEquals "generate-passwords" "0")}}'
          type: password
          required: true
        - name: user-db-password
          title: User Database Passowrd
          when: '{{repl (ConfigOptionEquals "generate-passwords" "0")}}'
          type: password
          required: true
---
apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: preflight-checks
spec:
  analyzers:
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.20.0"
              message: The application requires Kubernetes 1.20.0 or later, and recommends 1.21.0 or later.
              uri: https://www.kubernetes.io
          - warn:
              when: "< 1.21.0"
              message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.21.0 or later.
              uri: https://kubernetes.io
          - pass:
              message: Your cluster meets the recommended and required versions of Kubernetes.
    - containerRuntime:
        outcomes:
          - pass:
              when: "== containerd"
              message: containerd container runtime was found.
          - fail:
              message: Did not find containerd container runtime.
    - distribution:
        outcomes:
          - fail:
              when: "== docker-desktop"
              message: The application does not support Docker Desktop clusters.
          - fail:
              when: "== microk8s"
              message: The application does not support MicroK8s clusters.
          - fail:
              when: "== minikube"
              message: The application does not support minikube clusters.
          - pass:
              when: "== eks"
              message: EKS is a supported distribution.
          - pass:
              when: "== gke"
              message: GKE is a supported distribution.
          - pass:
              when: "== aks"
              message: AKS is a supported distribution.
          # Will be supported in the future
          - pass:
              when: "== kurl"
              message: kURL is a supported distribution.
          - pass:
              when: "== digitalocean"
              message: DigitalOcean is a supported distribution.
          - warn:
              message: Unable to determine the distribution of Kubernetes.
    - nodeResources:
        checkName: Total CPU Cores
        outcomes:
          - fail:
              when: "sum(cpuCapacity) < 2"
              message: The cluster must contain at least 2 cores, and should contain at least 4 cores.
          - warn:
              when: "sum(cpuCapacity) < 4"
              message: The cluster should contain at least 4 cores.
          - pass:
              message: There are at least 4 cores in the cluster.
---
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: support-bundle
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        selector:
          - app=amcefit
        namespace: '{{repl Namespace }}'
