---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: order-postgress-pass
  annotations:
    kots.io/exclude: '{{repl (ConfigOptionEquals "generate-passwords" "1") }}'
data:
  password: '{{repl ConfigOption "order-password" | Base64Encode}}'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: order-postgress-pass
  annotations:
    kots.io/exclude: '{{repl (ConfigOptionEquals "generate-passwords" "0") }}'
data:
  password: '{{repl RandomString 35 | Base64Encode }}'
