---
apiVersion: v1
type: Opaque
metadata:
  name: order-postgress-pass
  annotations:
    kots.io/exclude: '{{repl (ConfigOptionEquals "generate-passwords" "1") }}'
data:
  password: '{{repl ConfigOptionEquals "order-password" | Base64Encode}}'
---
apiVersion: v1
type: Opaque
metadata:
  name: order-postgress-pass
  annotations:
    kots.io/exclude: '{{repl (ConfigOptionEquals "generate-passwords" "0") }}'
data:
  password: '{{repl RandomString 35 | Base64Encode }}'
