apiVersion: v1
kind: Service
metadata:
  name: pos
  labels:
    app: acmefit
    service: pos
spec:
  ports:
    - name: http-pos
      protocol: TCP
      port: 7777
      targetPort: 7777
  selector:
    app: acmefit
    service: pos
  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: pos
  labels:
    app: acmefit
    service: pos
spec:
  selector:
    matchLabels:
      app: acmefit
      service: pos
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit
        service: pos
    spec:
      containers:
      - image: gcr.io/vmwarecloudadvocacy/acmeshop-pos:v0.1.0-beta
        name: pos
        env:
        - name: HTTP_PORT
          value: '7777'
        - name: DATASTORE
          value: 'REMOTE'
        - name: FRONTEND_HOST
          value: frontend.{{repl Namespace}}.svc.cluster.local
        ports:
        - containerPort: 7777
          name: pos
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kots.io/exclude: '{{repl (ConfigOptionEquals "tls-issuer-type" "issuer") }}'
    cert-manager.io/cluster-issuer: '{{repl (ConfigOption "tls-issuer-name" ) }}'
    ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app: acmefit
    service: pos
  name: pos
spec:
  rules:
    - host: pos.{{repl ConfigOption "domain"}}
    http:
      paths:
      - backend:
          service:
            name: pos
            port:
              number: 7777
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - pos.{{repl ConfigOption "domain"}}
    secretName: pos-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kots.io/exclude: '{{repl (ConfigOptionEquals "tls-issuer-type" "cluster-issuer") }}'
    cert-manager.io/issuer: '{{repl (ConfigOption "tls-issuer-name" ) }}'
    ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app: acmefit
    service: pos
  name: pos
spec:
  rules:
    - host: pos.{{repl ConfigOption "domain"}}
    http:
      paths:
      - backend:
          service:
            name: pos
            port:
              number: 7777
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - pos.{{repl ConfigOption "domain"}}
    secretName: pos-cert
