---
apiVersion: v1
type: Opaque
metadata:
  name: users-mongo-pass
data:
  password: bWlzdGFrZW5seS11dHRlcmx5LWFkdmVyc2VseS1keW5hbWljLWRyYWdvbg==
---
apiVersion: v1
type: Opaque
metadata:
  name: users-redis-pass
data:
  password: bWlzdGFrZW5seS11dHRlcmx5LWFkdmVyc2VseS1keW5hbWljLWRyYWdvbg==
