---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: users-mongo-pass
  annotations:
    kots.io/exclude: '{{repl (ConfigOptionEquals "generate-passwords" "1") }}'
data:
  password: '{{repl ConfigOption "user-db-password" | Base64Encode }}'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: user-mongo-pass
  annotations:
    kots.io/exclude: '{{repl (ConfigOptionEquals "generate-passwords" "0") }}'
data:
  password: '{{repl RandomString 35 | Base64Encode }}'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: user-redis-pass
  annotations:
    kots.io/exclude: '{{repl (ConfigOptionEquals "generate-passwords" "1") }}'
data:
  password: '{{repl ConfigOption "user-cache-password" | Base64Encode }}'
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: user-redis-pass
  annotations:
    kots.io/exclude: '{{repl (ConfigOptionEquals "generate-passwords" "0") }}'
data:
  password: '{{repl RandomString 35 | Base64Encode }}'
